<a href="https://colab.research.google.com/github/SkaiLord/ML-Lab/blob/main/ML_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 1

In [ ]:
import numpy as np

In [ ]:
# Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [ ]:
# Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array = array1.flatten()
print(flattened_array)
# Ravel flatten actual array w/o allocating new memory for new array -> immutable
# flattened_array = array1.ravel()
# print(flattened_array)

[1 2 3 2 4 5 1 2 3]


In [ ]:
# Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]])
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1, arr2))

True


In [ ]:
# Find the most frequent value and their indice(s) in the following arrays: x = np.array([1,2,3,4,5,1,2,1,1,1]) y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("X array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("Y array:")
print(y)

print("Most frequent value in the above array:")
print(np.bincount(y).argmax())

X array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1
Y array:
[1 1 1 2 3 4 2 4 3 3]
Most frequent value in the above array:
1


In [ ]:
# For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find Sum of all elements, Sum of all elements row-wise, Sum of all elements column-wise
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all elements:")
print(np.sum(gfg))
print("Sum of all elements row-wise:")
print(np.sum(gfg, axis=1))
print("Sum of all elements column-wise:")
print(np.sum(gfg, axis=0))

Sum of all elements:
45
Sum of all elements row-wise:
[[14]
 [16]
 [15]]
Sum of all elements column-wise:
[[20  9 16]]


In [ ]:
# For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]) find Sum of diagonal elements, Eigen values of matrix, Eigen vectors of matrix, Inverse of matrix, Determinant of matrix
n_matrix = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

print("Numpy Matrix is:\n",n_matrix)

# Sum of diagonal elements of a matrix
diag = np.diagonal(n_matrix)
print("Sum of Diagonal elements is:\n",sum(diag))

# Eigen Values and Vectors of matrix
w, v = np.linalg.eig(n_matrix)
print("Printing the Eigen values of the matrix:\n",
      w)
print("Printing Right Eigenvectors of the matrix:\n",
      v)

# INverse of Matrix
inverse_matrix = np.linalg.inv(n_matrix)
print("Inverse of matrix is:\n",inverse_matrix)

# Determinant of matrix
determinant_matrix = np.linalg.det(n_matrix)
print("Determinant of matrix is:\n",determinant_matrix)

Numpy Matrix is:
 [[55 25 15]
 [30 44  2]
 [11 45 77]]
Sum of Diagonal elements is:
 176
Printing the Eigen values of the matrix:
 [98.16835147 28.097044   49.73460452]
Printing Right Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix is:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix is:
 137180.0000000001


In [ ]:
# Multiply the following matrices and also find covariance between matrices using NumPy: i) p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] , ii) p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]]
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

# product of matrices
result = np.dot(p, q)

print(result)

# covariance matrix
print(np.cov(p))

# covariance matrix
print(np.cov(q))

# covariance matrix
print(np.cov(p, q))

# covariance matrix
print(np.cov(p, q, bias=1))

# covariance matrix
print(np.cov(p, q, bias=0))

[[16 19]
 [26 31]]
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
# For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),find inner, outer and cartesian product?
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:")
print(np.inner(x, y))
print("Outer product:")
print(np.outer(x, y))
print("Cartesian product:")
print(np.cross(x, y))

Inner product:
[[17 52]
 [13 62]]
Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
[[-20   4   7]
 [-84  36  20]]


**Question 2**

In [ ]:
import numpy as np

# Given array
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)
print("Absolute Value:\n", abs_array)



Absolute Value:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# ii. Percentiles of the flattened array, for each column, for each row
flattened = array.flatten()
percentiles_flattened = np.percentile(flattened, [25, 50, 75])

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

print("\nPercentiles of Flattened Array:", percentiles_flattened)
print("Percentiles for each Column:\n", percentiles_columns)
print("Percentiles for each Row:\n", percentiles_rows)


Percentiles of Flattened Array: [-3.5 -0.5  2.5]
Percentiles for each Column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each Row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
# iii. Mean, Median, and Standard Deviation of flattened array, of each column, and each row
mean_flattened = np.mean(flattened)
median_flattened = np.median(flattened)
std_flattened = np.std(flattened)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("\nMean, Median, Standard Deviation of Flattened Array:")
print("Mean:", mean_flattened, "Median:", median_flattened, "Std Dev:", std_flattened)

print("\nMean, Median, Standard Deviation for each Column:")
print("Mean:", mean_columns, "Median:", median_columns, "Std Dev:", std_columns)

print("\nMean, Median, Standard Deviation for each Row:")
print("Mean:", mean_rows, "Median:", median_rows, "Std Dev:", std_rows)



Mean, Median, Standard Deviation of Flattened Array:
Mean: -0.5 Median: -0.5 Std Dev: 3.8622100754188224

Mean, Median, Standard Deviation for each Column:
Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std Dev: [2.5 3.5 4.5]

Mean, Median, Standard Deviation for each Row:
Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std Dev: [2.05480467 4.78423336]


**Question 3**

In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)




Sorted array: [ 10  16  16  52  54  62 453]


In [ ]:
# ii. Indices of sorted array
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)



Indices of sorted array: [0 3 4 1 5 2 6]


In [ ]:
# iii. 4 smallest elements
smallest_elements = np.sort(array)[:4]
print("4 smallest elements:", smallest_elements)



4 smallest elements: [10 16 16 52]


In [ ]:
# iv. 5 largest elements
largest_elements = np.sort(array)[-5:]
print("5 largest elements:", largest_elements)

5 largest elements: [ 16  52  54  62 453]


In [ ]:
# Given array
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])



In [ ]:
# i. Integer elements only
integer_elements = array[array == np.floor(array)]
print("Integer elements only:", integer_elements)




Integer elements only: [1. 2. 3. 2.]


In [ ]:
# ii. Float elements only (excluding integers)
float_elements = array[array != np.floor(array)]
print("Float elements only:", float_elements)

Float elements only: [1.2 2.2]


**Question 4**

In [ ]:
import cv2
import numpy as np

def img_to_array(path):
    image = cv2.imread(path)

    if image is None:
        print("Error: Image not found or the path is incorrect.")
        return

    if len(image.shape) == 2:
        print("The image is in Grayscale.")
        np.savetxt("grayscale_image.txt", image, fmt='%d')
    elif len(image.shape) == 3:
        print("The image is in RGB.")
        reshaped_image = image.reshape(-1, image.shape[-1])
        np.savetxt("rgb_image.txt", reshaped_image, fmt='%d')
    else:
        print("Unsupported image format.")

    print("Image has been saved as a text file.")



In [ ]:
import numpy as np

def load_image_array(file_path, image_shape, is_rgb=False):
    if is_rgb:
        image_array = np.loadtxt(file_path, dtype=np.uint8)
        image_array = image_array.reshape(image_shape)
    else:
        image_array = np.loadtxt(file_path, dtype=np.uint8)

    return image_array